CREATE TABLE IF NOT EXISTS systems(
	id BIGSERIAL PRIMARY KEY,
	name TEXT NOT NULL,
	cameras INTEGER NOT NULL,
    link TEXT NOT NULL,
	model INTEGER NOT NULL,
	UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS detections (
	id BIGSERIAL PRIMARY KEY,
    system BIGINT NOT NULL,
	camera INTEGER NOT NULL,
	model TEXT NOT NULL,
	detection_time TIMESTAMP NOT NULL,
	image TEXT NOT NULL,
    person BOOLEAN NOT NULL,
	validated BOOLEAN DEFAULT false,
    FOREIGN KEY (system) REFERENCES systems(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS users (
	id BIGSERIAL PRIMARY KEY,
	username TEXT NOT NULL,
	email TEXT NOT NULL,
	password TEXT NOT NULL,
	UNIQUE (username)
);